name: lowder
description: A lightweight low-code development tool for Flutter.
version: 0.1.12
homepage: https://github.com/HCaseira/lowder_flutter
repository: https://github.com/HCaseira/lowder_flutter
documentation: https://github.com/HCaseira/lowder_flutter/wiki/
issue_tracker: https://github.com/HCaseira/lowder_flutter/issues

topics:
  - low-code
  - tool

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  shelf: '>=1.4.0 <2.0.0'
  shelf_router: '>=1.1.2 <2.0.0'
  shelf_static: '>=1.1.1 <2.0.0'

  flutter:
    sdk: flutter

  flutter_bloc: '>=8.1.1 <10.0.0'
  http: '>=1.0.0 <2.0.0'
  mask_text_input_formatter: '>=2.8.0 <3.0.0'
  intl: '>=0.17.0 <1.0.0'
  logging: '>=1.1.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
