name: lowder
description: A lightweight low-code development tool for Flutter to build your app with ease.
version: 0.1.11
homepage: https://github.com/HCaseira/lowder_flutter
repository: https://github.com/HCaseira/lowder_flutter
documentation: https://github.com/HCaseira/lowder_flutter/wiki/
issue_tracker: https://github.com/HCaseira/lowder_flutter/issues

topics:
  - low-code
  - tool

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  shelf: ^1.3.2
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  http: ^1.2.0
  mask_text_input_formatter: ^2.4.0
  uuid: ^4.2.2
  intl: ^0.19.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
